package com.simulation.screens.loading;

public class LSVan {
    public static void main(String[] args) {

	}
	
	public void display() {
        int frameCount = 0;

        while (frameCount <= 20) {
            int currentFrame = frameCount % 4;

            System.out.print("\033[H\033[2J");
            System.out.flush();

            if (currentFrame == 0) {
                System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                               █████                                                                                                ██");
                System.out.println("██                                                                                              ██   █                                                                                                ██");
                System.out.println("██                                                                                            ███    ████                                                                                             ██");
                System.out.println("██                                                                                            █         █                                                                                             ██");
                System.out.println("██                                                                    █████████            ████         ███             █████████                                                                     ██");
                System.out.println("██                                                                    █       ██████      ██              ██       ██████       █                                                                     ██");
                System.out.println("██                                                                    █            █      █                █      ██            █                                                                     ██");
                System.out.println("██                                                                    █            ████   ██████████████████   ████             █                                                                     ██");
                System.out.println("██                                                                    █               █                        █                █                                                                     ██");
                System.out.println("██                                                                    █            ████                        █████            █                                                                     ██");
                System.out.println("██                                                                    ████    ██████        ███████████████        ██████    ████                                                                     ██");
                System.out.println("██                                                                       █   ██          ████             ████          █    █                                                                        ██");
                System.out.println("██                                                          ██████████   █████      ██████                   ██████     ██████     █████████████                                                      ██");
                System.out.println("██                                                         ██        ██            ██                             ██               █           ██                                                     ██");
                System.out.println("██                                                    ██████          █         ████                               ████         ████            █                                                     ██");
                System.out.println("██                                                    █               █      ████                                     ████      █               █                                                     ██");
                System.out.println("██                                                    █            ████    ███                                           ███    ████            █                                                     ██");
                System.out.println("██                                                    ██           █       █                                               █       █          ███                                                     ██");
                System.out.println("██                                                     ███         █     ███                                               ███     █         ██                                                       ██");
                System.out.println("██                                                       ███     ███     █                                                   █     ███       █                                                        ██");
                System.out.println("██                                                         ████  █    ████               _____________________               ████    ████  ███                                                        ██");
                System.out.println("██                                                            ████    █                 |__  _____  _____  ___\\                 █       ████                                                          ██");
                System.out.println("██                                                                  ███                 |  ||     ||     ||    \\                ███                                                                   ██");
                System.out.println("██                                                    █████████    ██                   |__||_____||_____||_____\\                 ██    █████████                                                     ██");
                System.out.println("██                                                 ████       █    █                    |    _          -||_    |                  █    █       ██████                                                ██");
                System.out.println("██                                             ██████         █   ██                    |___/ \\__________|/ \\___/                  ██   █            ███                                              ██");
                System.out.println("██                                            ██              █   █                         \\_/           \\_/                       █   █              ██                                             ██");
        	System.out.println("██                            ░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓                           ██");
        	System.out.println("██                            █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           ██");
        	System.out.println("██                            █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                           Travelling...                                                                                            ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("██                                                                                                                                                                                                    ██");
                System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");

            } else if (currentFrame == 1) {
   		System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                          █████                                                                                                     ██");
        	System.out.println("██                                                                                          █   █                                                                                                     ██");
        	System.out.println("██                                                                                        ███   ████                                                                                                  ██");
        	System.out.println("██                                                                                        █        █                   █████████                                                                      ██");
        	System.out.println("██                                                                                       ██        ██████         ██████       █                                                                      ██");
        	System.out.println("██                                                                                      ██              ██       ██            █                                                                      ██");
        	System.out.println("██                                                                   █████████          █                █    ████             █                                                                      ██");
        	System.out.println("██                                                                 ███       ████████   ██████████████████    █                █                                                                      ██");
        	System.out.println("██                                                                 █                █                         █████            █                                                                      ██");
        	System.out.println("██                                                                 █             ████                             ██████    ████                                                                      ██");
        	System.out.println("██                                                                 █             █          ███████████████            █    █                                                                         ██");
        	System.out.println("██                                                                 █          ████       ████             ████         ██████    █████████████                                                        ██");
        	System.out.println("██                                                                 ████    ████     ██████                   ██████              █           ██                                                       ██");
        	System.out.println("██                                                                    █   ██       ██                             ██          ████            █                                                       ██");
        	System.out.println("██                                                       ██████████   █████     ████                               ████       █               █                                                       ██");
        	System.out.println("██                                                      ██        ██         ████                                     ████    ████            █                                                       ██");
        	System.out.println("██                                                 ██████          █       ███                                           ███     █          ███                                                       ██");
        	System.out.println("██                                                 █               █       █                                               █     █         ██                                                         ██");
       		System.out.println("██                                                 █            ████     ███                                               ███   ███       █                                                          ██");
        	System.out.println("██                                                 ██           █        █                                                   █     ████  ███                                                          ██");
        	System.out.println("██                                                  ███         █     ████               _____________________               ████     ████                                                            ██");
        	System.out.println("██                                                    ███     ███     █                 |__  _____  _____  ___\\                 █                                                                     ██");
        	System.out.println("██                                                      ████  █     ███                 |  ||     ||     ||    \\                ███    █████████                                                      ██");
        	System.out.println("██                                                         ████    ██                   |__||_____||_____||_____\\                 ██   █       ██████                                                 ██");
        	System.out.println("██                                                                 █                    |    _          -||_    |                  █   █            ███                                               ██");
        	System.out.println("██                                                    █████████   ██                    |___/ \\__________|/ \\___/                  ██  █              ██                                              ██");
        	System.out.println("██                                                 ████       █   █                         \\_/           \\_/                       █  █               ██                                             ██");
        	System.out.println("██                            ░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓                           ██");
        	System.out.println("██                            █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           ██");
        	System.out.println("██                            █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                           Travelling...                                                                                            ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");

            } else if (currentFrame == 2) {
   		System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                   ██████                                                                                                           ██");
        	System.out.println("██                                                                                   █    █                        ██████                                                                             ██");
        	System.out.println("██                                                                                  ██    █████                  ███    ██                                                                            ██");
        	System.out.println("██                                                                                  █         █               ████       █                                                                            ██");
        	System.out.println("██                                                                                  █         ██████       ████          █                                                                            ██");
        	System.out.println("██                                                                                  █              ██   ████             █                                                                            ██");
        	System.out.println("██                                                                                  █               █   █                █                                                                            ██");
        	System.out.println("██                                                               ███████████        █    ████████████   ████             █                                                                            ██");
        	System.out.println("██                                                              ██         ███████  ██████                 ███████    ████       █████████                                                            ██");
        	System.out.println("██                                                              █                █                               ██████      █████       ██                                                           ██");
        	System.out.println("██                                                              █                █          ███████████████               ████            █                                                           ██");
        	System.out.println("██                                                              █              ███       ████             ████            █               █                                                           ██");
        	System.out.println("██                                                              █           ████    ██████                   ██████       ██              █                                                           ██");
        	System.out.println("██                                                              ██       ████      ██                             ██       ███          ███                                                           ██");
        	System.out.println("██                                                               ████   ██      ████                               ████      ██        ██                                                             ██");
        	System.out.println("██                                                                  █████    ████                                     ████    ██       █                                                              ██");
        	System.out.println("██                                                       ████████          ███                                           ███   ████  ███                                                              ██");
        	System.out.println("██                                                  ██████      ████       █                                               █      ████                                                                ██");
       		System.out.println("██                                                 ██              █     ███                                               ███            ██████                                                      ██");
        	System.out.println("██                                                 █               █     █                                                   █        █████    ██████                                                 ██");
        	System.out.println("██                                                 █            ████  ████               _____________________               ████     █             ███                                               ██");
        	System.out.println("██                                                 ██           █     █                 |__  _____  _____  ___\\                 █     █               ██                                              ██");
        	System.out.println("██                                                  ███         █   ███                 |  ||     ||     ||    \\                ███   ██               █                                              ██");
        	System.out.println("██                                                    ███     ███  ██                   |__||_____||_____||_____\\                 ██   █            ████                                              ██");
        	System.out.println("██                                                      ████  █    █                    |    _          -||_    |                  █   █      ███████                                                 ██");
        	System.out.println("██                                                         ████   ██                    |___/ \\__________|/ \\___/                  ██  ████████                                                       ██");
        	System.out.println("██                                                                █                         \\_/           \\_/                       █                                                                 ██");
        	System.out.println("██                            ▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░                           ██");
        	System.out.println("██                            █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           ██");
        	System.out.println("██                            █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                           Travelling...                                                                                            ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            } else {
   		System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                █████                                                                                               ██");
        	System.out.println("██                                                                                              ███   ████                                                                                            ██");
        	System.out.println("██                                                                                              █        █                                                                                            ██");
        	System.out.println("██                                                                                            ███        ███                                                                                          ██");
        	System.out.println("██                                                                   ██████                ████            █               ███████                                                                    ██");
        	System.out.println("██                                                                   █    ██████           █               ██       ████████     █                                                                    ██");
        	System.out.println("██                                                                  ██         ████████    █                █    ████            █                                                                    ██");
        	System.out.println("██                                                                  █                 █    ██████████████████   ██               █                                                                    ██");
        	System.out.println("██                                                                  █                ██                         █                █                                                                    ██");
        	System.out.println("██                                                                  █             ████                          ██████           █                                                                    ██");
        	System.out.println("██                                                                  █           ███         ███████████████          ███       ███                                                                    ██");
        	System.out.println("██                                                                  █    ████████        ████             ████         █       █                                                                      ██");
        	System.out.println("██                                                                  ██████          ██████                   ██████    ████  ███                                                                      ██");
        	System.out.println("██                                                    ███████████                  ██                             ██      ████       █████████████                                                    ██");
        	System.out.println("██                                                    █         ███████         ████                               ████          █████           █                                                    ██");
        	System.out.println("██                                                    █               █      ████                                     ████      ██               █                                                    ██");
        	System.out.println("██                                                    █               █    ███                                           ███    █                █                                                    ██");
        	System.out.println("██                                                    █              ██    █                                               █    ███              █                                                    ██");
       		System.out.println("██                                                    █           ████   ███                                               ███    ███         ████                                                    ██");
        	System.out.println("██                                                    ██       ████      █                                                   █      █       ███                                                       ██");
        	System.out.println("██                                                     █████   ██     ████               _____________________               ████   ██   ████                                                         ██");
        	System.out.println("██                                                         █████      █                 |__  _____  _____  ___\\                 █    █████                                                            ██");
        	System.out.println("██                                                                  ███                 |  ||     ||     ||    \\                ███                                                                   ██");
        	System.out.println("██                                                   ████████      ██                   |__||_____||_____||_____\\                 ██      ████████                                                    ██");
        	System.out.println("██                                                ████      ████   █                    |    _          -||_    |                  █   ████      ████                                                 ██");
        	System.out.println("██                                             ████            █  ██                    |___/ \\__________|/ \\___/                  ██  █            ████                                              ██");
        	System.out.println("██                                            ██               █  █                         \\_/           \\_/                       █  █               ██                                             ██");
        	System.out.println("██                            ░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░░░▓▓▓▓▓░░░░░░░░                           ██");
        	System.out.println("██                            █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           ██");
        	System.out.println("██                            █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                           Travelling...                                                                                            ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("██                                                                                                                                                                                                    ██");
        	System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            }

            frameCount++;

            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}