package com.simulation.screens.narratives;

public class GatewayToBicolandia {
    public static void main(String[] args) {

	}
	
	public void display() {
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                               G A T E W A Y  T O  B I C O L A N D I A                                                                              ██");
        System.out.println("██                                                                                    Santa Elena, Camarines Norte                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     The Gateway to Bicolandia Arch  is a prominent landmark situated along the National Road in                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     Santa Elena,  Camarines Norte.  Located at the northern border  of the Bicol Region,  Santa                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     Elena  is often called the  \"Gateway to Bicolandia,\"  welcoming travelers  into the region.                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     The arch serves as a symbol of the town's role as a growth center, marking its proximity to                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     popular tourist destinations in Bicol.  The structure features traditional Bicolano motifs,                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     including the iconic \"salakot\" (native wide-brimmed hat) and images of Mayon Volcano, which                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     represent the region's cultural heritage and natural beauty.  The arch is not only a visual                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     andmark but also an important symbol  of the region’s rich history and identity.  It offers                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     visitors a memorable introduction to the vibrant culture and landscapes of Bicol, making it                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                     a must-see spot for travelers.                                                                                                                 ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                R (Restart)                                                M (End)                                                                                              ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
    }
}