package com.simulation.screens.narratives;

public class MananapFalls {
    public static void main(String[] args) {

	}
	
	public void display() {
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                      M A N A N A P  F A L L S                                                                                      ██");
        System.out.println("██                                                                                    San Vicente, Camarines Norte                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   Mananap Falls, located in Barangay San Jose  within the municipality of San Vicente,  Camarines                                                  ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   Norte, is a captivating natural attraction  known for its beauty. The waterfall stands about 60                                                  ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   depended on San Miguel Bay  for their  daily needs  and sustenance.  Situated along the eastern                                                  ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   60 feet tall,  with crystal-clear waters  cascading into a deep basin,  creating a peaceful and                                                  ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   refreshing atmosphere perfect for relaxation. The area around the falls is ideal for activities                                                  ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   like swimming, freshwater fishing, camping, and nature watching,  offering visitors a chance to                                                  ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   connect with nature.  The surrounding forest, lush and dense,  holds historical significance as                                                  ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   it was reportedly a refuge for Katipunan rebels  during the Philippine Revolution  (1896-1898).                                                  ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   The  pristine environment  and historical importance  make Mananap Falls  a unique destination.                                                  ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   With its tranquil ambiance and rich history, the falls remain a hidden gem for nature lovers.                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                R (Restart)                                                M (End)                                                                                              ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
    }
}