package com.simulation.screens.narratives;

public class MercedesFishPort {
    public static void main(String[] args) {

	}
	
	public void display() {
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                  M E R C E D E S  F I S H  P O R T                                                                                 ██");
        System.out.println("██                                                                                      Mercedes, Camarines Norte                                                                                     ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   The Mercedes Fish Port, located in the coastal municipality of Mercedes in Camarines Norte, is                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   a major hub for the region's fishing industry, thriving with local activity. Mercedes' fishing                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   industry dates back to the Spanish colonial era (16th-19th century),  when coastal communities                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   depended on San Miguel Bay  for their daily needs  and sustenance.  Situated along the eastern                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   part of the province,  the northern section faces the Pacific Ocean at the mouth of San Miguel                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   Bay,  earning Mercedes  the title  \"The Belle of the Pacific.\"  A distinctive  feature  of the                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   Mercedes Fish Port  is the traditional \"Bulungan\"  or  whispered bidding practice,  where fish                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   fish prices  are quietly  negotiated between  buyers and  sellers. The  port offers  a vibrant                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   atmosphere,  where  the local  fishing community's  rich history  can be  witnessed firsthand,                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   giving visitors a unique glimpse into the region's maritime culture.                                                                             ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                R (Restart)                                                M (End)                                                                                              ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
    }
}