package com.simulation.screens.narratives;

public class MountLabo {
    public static void main(String[] args) {

	}
	
	public void display() {
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                         M O U N T  L A B O                                                                                         ██");
        System.out.println("██                                                                                        Labo, Camarines Norte                                                                                       ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    Nestled in the heart  of the  Bicol  Peninsula,  Mt. Labo is a breathtaking destination  for                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    adventurous travelers  and  nature lovers  alike.  Standing at  1,544 meters,  this  dormant                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    andesitic stratovolcano  offers  stunning  panoramic  views  of the surrounding  landscapes,                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    making it an ideal spot  for hiking and photography.  The mountain provides visitors with an                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    opportunity  to experience diverse scenery  and enjoy the beauty of nature.  Mt. Labo is not                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    just a scenic spot; it also serves as a vital watershed, supplying essential water resources                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    to nearby communities.  The cool mountain air  and varied climate create distinct ecological                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    zones, making each part of the journey unique.  The trek up Mt. Labo  offers both a physical                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    challenge and a chance to immerse oneself in the natural beauty of the Bicol region,  making                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    it a  rewarding adventure.  For those  seeking an escape  into nature,  Mt. Labo  provides a                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                    peaceful retreat.                                                                                                                               ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                R (Restart)                                                M (End)                                                                                              ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
    }
}