package com.simulation.screens.narratives;

public class StPeter {
    public static void main(String[] args) {

	}
	
	public void display() {
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                S A I N T  P E T E R  T H E  A P O S T L E  P A R I S H  C H U R C H                                                                ██");
        System.out.println("██                                                                                      Vinzons, Camarines Norte                                                                                      ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                 The St. Peter the Apostle Parish Church is a Roman Catholic church located in Vinzons, formerly as                                                 ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                 Tacboan, in Camarines Norte.  Established in 1581 by Franciscan friars, the church was constructed                                                 ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                 in 1611  under the leadership of Rev. Fr. Juan de Losar,  OFM,  making it the oldest church in the                                                 ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                 province.  Over the years, the church has endured several reconstructions due to natural disasters                                                 ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                 and fires.  A significant event in its history occurred on December 26, 2012,  when the church was                                                 ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                 gutted by fire, but it was reopened to the public on June 29, 2015,  coinciding with the Feast Day                                                 ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                 of St. Peter. Despite its challenges,  the church remains a symbol of resilience and faith for the                                                 ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                 local community.  Its enduring beauty and historical significance  make it a must-see landmark for                                                 ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                 visitors in the region.                                                                                                                            ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                R (Restart)                                                M (End)                                                                                              ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                   █████████████████████████████████████                    █████████████████████████████████████                                                   ██");
        System.out.println("██                                               ████████                          ████████████          ████████████                          ████████                                               ██");
        System.out.println("██                                                                                           ██████████████                                                                                           ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("██                                                                                                                                                                                                    ██");
        System.out.println("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
    }
}